Repository walmartlabs/lacinia, pull requests merged in 2018-07, with the labels that each got.

#202 Introspection: Properly output default values for field arguments as per the spec
  CHANGES.md
  dev-resources/input-object-default-value-schema.edn
  dev-resources/list-default-value-schema.edn
  dev-resources/non-string-default-value-schema.edn
  project.clj
  resources/com/walmartlabs/lacinia/introspection.edn
  src/com/walmartlabs/lacinia/introspection.clj
  test/com/walmartlabs/introspection_test.clj
Labels: bug, spec compliance

#203 Supplying invalid keys to an input object results in a confusing and unhelpful error
  dev-resources/input-object-schema.edn
  src/com/walmartlabs/lacinia/parser.clj
  test/com/walmartlabs/input_objects_test.clj
Labels: bug

#207 Allow vars to be passed as resolver
  src/com/walmartlabs/lacinia/schema.clj
  test/com/walmartlabs/lacinia/expound_tests.clj
Labels: enhancement

#208 Don't fail the member type test if the resolved value is nil
  src/com/walmartlabs/lacinia/schema.clj
  test/com/walmartlabs/lacinia/unions_test.clj
Labels: bug

#210 Restore broken compatibility with Clojure 1.8
  src/com/walmartlabs/lacinia/internal_utils.clj
Labels: bug

#211 Make error maps in the result conform to the June 2018 specification
  CHANGES.md
  dev-resources/errors.edn
  dev-resources/introspection.edn
  dev-resources/perf.clj
  docs/_examples/errors-result.edn
  docs/conf.py
  docs/resolve/resolve-as.rst
  perf/benchmarks.csv
  src/com/walmartlabs/lacinia/executor.clj
  src/com/walmartlabs/lacinia/parser.clj
  src/com/walmartlabs/lacinia/parser/common.clj
  src/com/walmartlabs/lacinia/schema.clj
  src/com/walmartlabs/lacinia/util.clj
  test/com/walmartlabs/input_objects_test.clj
  test/com/walmartlabs/lacinia/custom_scalars_test.clj
  test/com/walmartlabs/lacinia/enums_test.clj
  test/com/walmartlabs/lacinia/merge_selections_test.clj
  test/com/walmartlabs/lacinia/nested_list_tests.clj
  test/com/walmartlabs/lacinia/parser/query_test.clj
  test/com/walmartlabs/lacinia/resolve_test.clj
  test/com/walmartlabs/lacinia/resolver_errors_test.clj
  test/com/walmartlabs/lacinia/timings_test.clj
  test/com/walmartlabs/lacinia/validator_test.clj
  test/com/walmartlabs/lacinia/variables_test.clj
  test/com/walmartlabs/lacinia_test.clj
Labels: enhancement, spec compliance

#212 Add support for block strings (from the June 2018 GraphQL specification)
  CHANGES.md
  dev-resources/blockquote.sdl
  dev-resources/parser/literals.edn
  dev-resources/parser/literals.gql
  resources/com/walmartlabs/lacinia/Graphql.g4
  resources/com/walmartlabs/lacinia/schema.g4
  src/com/walmartlabs/lacinia/parser/common.clj
  src/com/walmartlabs/lacinia/parser/query.clj
  src/com/walmartlabs/lacinia/parser/schema.clj
  test/com/walmartlabs/lacinia/parser/schema_test.clj
Labels: enhancement, spec compliance

#215 Handle all variations of how enum values are defined when injecting descriptions
  src/com/walmartlabs/lacinia/internal_utils.clj
  src/com/walmartlabs/lacinia/util.clj
  test/com/walmartlabs/lacinia/util_test.clj
Labels: bug
