Repository walmartlabs/lacinia, pull requests merged in 2018-06, with the labels that each got.

#197 Remove a race condition between registering a callback on a ResolverResultPromise, and delivering it
  src/com/walmartlabs/lacinia/resolve.clj
Labels: bug

#199 Fix typos in the tutorial
  docs/tutorial/prereqs.rst
Labels: documentation

#198 Tweak definitions to get better expound output
  CHANGES.md
  dev-resources/user.clj
  project.clj
  src/com/walmartlabs/lacinia/expound.clj
  src/com/walmartlabs/lacinia/schema.clj
  test/com/walmartlabs/lacinia/expound_tests.clj
  test/com/walmartlabs/lacinia/schema_test.clj
Labels: enhancement
