Repository walmartlabs/lacinia, pull requests merged in 2019-02, with the labels that each got.

#264 Make exceptions more consistent and concise
  dev-resources/com/walmartlabs/test_utils.clj
  src/com/walmartlabs/lacinia/executor.clj
  src/com/walmartlabs/lacinia/internal_utils.clj
  src/com/walmartlabs/lacinia/parser.clj
  src/com/walmartlabs/lacinia/schema.clj
  src/com/walmartlabs/lacinia/validation/scalar_leafs.clj
  src/com/walmartlabs/lacinia/validator.clj
  test/com/walmartlabs/input_objects_test.clj
  test/com/walmartlabs/interface_test.clj
  test/com/walmartlabs/lacinia/arguments_test.clj
  test/com/walmartlabs/lacinia/custom_scalars_test.clj
  test/com/walmartlabs/lacinia/directives_test.clj
  test/com/walmartlabs/lacinia/enums_test.clj
  test/com/walmartlabs/lacinia/expound_tests.clj
  test/com/walmartlabs/lacinia/field_tests.clj
  test/com/walmartlabs/lacinia/interfaces_test.clj
  test/com/walmartlabs/lacinia/merge_selections_test.clj
  test/com/walmartlabs/lacinia/parser/schema_test.clj
  test/com/walmartlabs/lacinia/schema_test.clj
  test/com/walmartlabs/lacinia/unions_test.clj
  test/com/walmartlabs/lacinia/validator_test.clj
  test/com/walmartlabs/lacinia_test.clj
Labels: enhancement

#258 Change schema parser to accept &-separated interfaces
  dev-resources/mult-inheritance.sdl
  resources/com/walmartlabs/lacinia/schema.g4
  src/com/walmartlabs/lacinia/parser/schema.clj
Labels: bug, spec compliance

#269 GraphQL schema parsing support for extend type and empty type
  resources/com/walmartlabs/lacinia/schema.g4
  src/com/walmartlabs/lacinia/parser/common.clj
  src/com/walmartlabs/lacinia/parser/schema.clj
  test/com/walmartlabs/lacinia/parser/schema_test.clj
Labels: spec compliance
