Repository walmartlabs/lacinia, pull requests merged in 2019-08, with the labels that each got.

#290 Improvements to the executor namespace preview API
  CHANGES.md
  dev-resources/perf.clj
  project.clj
  src/com/walmartlabs/lacinia/executor.clj
  test/com/walmartlabs/lacinia/selections_tests.clj
Labels: enhancement

#294 Fix an issue where error paths in collections were missing indices
  src/com/walmartlabs/lacinia/schema.clj
  test/com/walmartlabs/lacinia_test.clj
Labels: bug, spec compliance

#295 Allow a var, as well as a function, for streamers and default resolver to support REPL-oriented development
  src/com/walmartlabs/lacinia/schema.clj
Labels: bug
