Repository walmartlabs/lacinia, pull requests merged in 2021-11, with the labels that each got.

#381 Update documentation with invoke streamer example
  docs/_examples/invoke-streamer.edn
  docs/subscriptions/streamer.rst
Labels: documentation

#386 Remove ResolverResult edge case, optimize null collapse where not value can be null
  CHANGES.md
  perf/benchmarks.csv
  src/com/walmartlabs/lacinia/executor.clj
  src/com/walmartlabs/lacinia/resolve.clj
  src/com/walmartlabs/lacinia/schema.clj
  src/com/walmartlabs/lacinia/select_utils.clj
  test/com/walmartlabs/lacinia/resolve_test.clj
Labels: enhancement

#387 Restore ability to add multiple errors at once
  CHANGES.md
  src/com/walmartlabs/lacinia/resolve.clj
  test/com/walmartlabs/lacinia/resolver_errors_test.clj
Labels: bug

#388 Fix resolve-as with nil error returning nil (in 1.1-alpha-4)
  src/com/walmartlabs/lacinia/resolve.clj
  test/com/walmartlabs/lacinia/resolver_errors_test.clj
Labels: bug

#391 Add support for extending unions
  resources/com/walmartlabs/lacinia/schema.g4
  src/com/walmartlabs/lacinia/parser/schema.clj
  src/com/walmartlabs/lacinia/resolve.clj
  test/com/walmartlabs/lacinia/parser/schema_test.clj
Labels: spec compliance

#394 Restore support for ResolverResult passed to subscription stream callback
  deps.edn
  dev-resources/subscriptions-schema.edn
  docs/subscriptions/streamer.rst
  project.clj
  src/com/walmartlabs/lacinia/executor.clj
  test/com/walmartlabs/lacinia/subscription_tests.clj
Labels: bug
