Repository walmartlabs/lacinia, pull requests merged in 2023-04, with the labels that each got.

#441 Apply default resolver to all subscriptions missing :resolve
  src/com/walmartlabs/lacinia/schema.clj
Labels: bug

#442 Set up GitHub actions CI builds
  .circleci/config.yml
  .github/workflows/config.yml
  README.md
Labels: enhancement

#444 Update index.rst
  docs/resolve/index.rst
Labels: documentation

#443 Add support for @deprecated directives on :argument-definition, :input-field-definition
  src/com/walmartlabs/lacinia/schema.clj
  test/com/walmartlabs/lacinia/directives_test.clj
Labels: spec compliance
